In [2]:
import cv2
import numpy as np

## Double

In [3]:
grey = cv2.imread("./rabbit.jpg", cv2.IMREAD_GRAYSCALE)

In [4]:
grey_db = np.double(grey)

In [5]:
# grey_db는 잘 안나온다
cv2.imshow("grey",grey)
cv2.imshow("grey_db", grey_db)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# grey_db를 255로 나누었더니 잘 나온다
cv2.imshow("grey_db", grey_db)
cv2.imshow("grey_db/255", grey_db/255)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# 스케일을 변경해보면, 512로 나누면 값이 0에 더 가까워지므로 원본보다 어두워지고 128로 나누면 1에 더 가까워지므로 밝아진다.
cv2.imshow("grey_db/512", grey_db/512)
cv2.imshow("grey_db/128", grey_db/128)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
grey[0,0], grey_db[0,0]

(75, 75.0)

In [9]:
def im2double(im):
    min_val = np.min(im.ravel())
    max_val = np.max(im.ravel())
    out = (im.astype('float') - min_val) / (max_val - min_val)
    return out

In [10]:
out = im2double(grey)

In [11]:
cv2.imshow("grey_db/255", grey_db/255)
cv2.imshow("out", out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
out[0,0] == grey_db[0,0]/255

True

## Binary

In [53]:
binary = grey>100
binary2 = grey>200

In [54]:
grey

array([[ 75,  83,  77, ..., 154, 154, 154],
       [ 77,  80,  74, ..., 152, 152, 152],
       [ 83,  82,  77, ..., 147, 147, 147],
       ...,
       [194, 191, 201, ..., 205, 203, 199],
       [194, 191, 201, ..., 205, 203, 199],
       [194, 191, 201, ..., 205, 203, 199]], dtype=uint8)

In [55]:
binary

array([[False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [56]:
binary = binary.astype(int)
binary = np.double(binary)
binary2 = binary2.astype(int)
binary2 = np.double(binary2)

In [57]:
# logic형(True,False)을 int형(0,1)으로 바꾸고 이걸 다시 double형으로 바꿔줘야함
binary

array([[0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [61]:
# 100 과 200 의 차이 -> 200에서는 진짜 밝은 픽셀들만 흰색 처리가 되므로 상대적으로 더 대비가 크다 
cv2.imshow("grey", grey)
cv2.imshow("binary_100", binary)
cv2.imshow("binary_200", binary2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Bit planes

In [39]:
np.floor(65/32)

2.0

In [31]:
grey0 = np.mod(grey,2)
grey1 = np.mod(np.floor(grey/2),2)
grey3 = np.mod(np.floor(grey/8),2)
grey5 = np.mod(np.floor(grey/32),2)
grey7 = np.mod(np.floor(grey/128),2)
cv2.imshow("grey0", grey0)
cv2.imshow("grey1", grey1)
cv2.imshow("grey3", grey3)
cv2.imshow("grey5", grey5)
cv2.imshow("grey7", grey7)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Spatial resolution

In [12]:
grey.shape

(467, 467)

In [13]:
grey256 = cv2.resize(cv2.resize(grey, (256,256)), (467,467))

In [21]:
cv2.imshow("grey", grey)
cv2.imshow("grey256", cv2.resize(cv2.resize(grey, (256,256)), (467,467)))
cv2.imshow("grey128", cv2.resize(cv2.resize(grey, (128,128)), (467,467)))
cv2.imshow("grey64", cv2.resize(cv2.resize(grey, (64,64)), (467,467)))
cv2.imshow("grey32", cv2.resize(cv2.resize(grey, (32,32)), (467,467)))
cv2.waitKey(0)
cv2.destroyAllWindows()